config/routes.rb
Rails.application.routes.draw do
  resources :users, :events, :venues
  get 'signup' => 'users#new'

  root 'home#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get 'attend_event' => 'events#attend'
  get 'unattend_event' => 'events#unattend'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  # def make_admin
  #   Attendance.where(user_id:current_user.id).where(event_id:event.id).take
  # end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :venue
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
  validates :name, presence: true
  validates :venue_id, presence: true
  # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # def make_admin
  #   Attendance.where(user_id:current_user.id).where(event_id:event.id).take
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :attendances
  has_many :events, through: :attendances
  has_many :venues
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :nickname, presence: true, uniqueness: true
  validates :email, uniqueness: true, confirmation: true
  validates :email_confirmation, presence: true
  validates :password_digest, confirmation: true
  validates :password_digest_confirmation, presence: true
  # has_secure_password

  def attending(event)
    attendances.where(event_id:event.id).count > 0
  end
  def has_events
    events.count != 0
  end
  def has_venues
    venues.count != 0
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def require_user
    redirect_to login_path unless current_user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :require_user, only: [:new]
  before_action :set_event, only: [:destroy,:edit,:update]
  def index
    @events = current_user.attendances.where(admin:false).limit(25)
    @is_admin = Attendance.where(user_id:current_user.id).where(admin:true)
    @admin_events =  current_user.attendances.where(admin:true)
  end
  def new
    @event = current_user.events.new
    @venues = current_user.venues
  end
  def attend
    Attendance.create(user_id: current_user.id,event_id:params[:id])
    redirect_to :back, notice: "you are attending #{Event.find(params[:id]).name}"
  end
  def show
    @event = Event.find(params[:id])
    @venue = @event.venue
  end
  def edit
    @venues = current_user.venues
  end
  def unattend
    Attendance.where(user_id: current_user.id).where(event_id:params[:id]).take.destroy
    redirect_to :back, notice: "you are not attending #{Event.find(params[:id]).name} anymore"
  end
  def create
    respond_to do |format|
      if event = current_user.events.create(event_params)
        attending = Attendance.where(user_id:current_user.id).where(event_id:event.id).take
        attending.admin = true
        attending.save
        format.html { redirect_to root_path, notice: 'event was successfully created.' }
        #format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to root_path, notice: 'event was successfully updated.' }
        #format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_path, notice: 'Event was successfully destroyed.' }
    end
  end

  def set_event
    @event = current_user.events.find(params[:id])
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :start_date,:end_date,:end_time,:venue_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pages = {}
    @pages[:page] = (params[:page] || 1).to_i
    @pages[:last_page] = Event.all.count / 10
    offset = (@pages[:page] - 1) * 10
    @events = Event.order(created_at: :desc).limit(10).offset(offset).all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.password_digest == params[:session][:password]#@user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      if @user
        #flash.now[:index] = "Wrong Password"
        redirect_to login_path, flash:{session: "Please try your password again"}
      else
        redirect_to login_path, flash:{session: "No user found"}
      end

    end
  end
  def destroy
    reset_session
    redirect_to root_path, flash:{session: "You logged out"}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events

  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { redirect_to new_user_path, notice: 'There was a problem please try again' }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name,:last_name,:nickname,:password_digest, :email,:password_digest_confirmation,:password,:password_confirmation, :email_confirmation, :info, :bio,:avatar)
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_venue, only: [:destroy]
  def new
    @venue = current_user.venues.new
  end
  def index
    @venues = current_user.venues.all
  end
  def create
    @venue = current_user.venues.new(user_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to root_path, notice: 'venue was successfully created.' }
        #format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_path, notice: 'venue was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_venue
    @venue = current_user.venues.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:venue).permit(:name, :info, :address,:city,:country,:state,:zip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
  <!--<#% if @event.errors.any? %>-->
    <!--<div id="error_explanation">-->
      <!--<h2><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>-->

      <!--<ul>-->
        <!--<%# @event.errors.full_messages.each do |message| %>-->
          <!--<li><%#= message %></li>-->
        <!--<%# end %>-->
      <!--</ul>-->
    <!--</div>-->
  <!--<%# end %>-->

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <!--<div class="field">-->
    <%#= f.label :image %><br>
    <!--<#%= f.file_field :image, as: :file %>-->
  <!--</div>-->
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_field :end_time %>
  </div>
  <%= f.collection_select(:venue_id, @venues.all, :id, :name) %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.haml
%h1 Edit Event
= render 'form'

app/views/events/index.html.erb
<%= link_to 'BACK', :back, class:"btn" %>
<%= link_to 'New Venue', new_venue_path, class:"btn" %>
<%= link_to 'New Event', new_event_path, class:"btn" %><br><br>
<h3>My hosted events:</h3>
<% @admin_events.each do |attendance| %>
  <%= attendance.event.name %>
    <%= link_to 'edit',edit_event_path(id:attendance.event.id),class:"btn" %>
  <%= link_to "delete", attendance.event, method: "delete", class:"btn",data: { confirm: 'Are you sure?' } %>
  <br>
<% end %>
<br><br>
<h3>Events I'm going to:</h3>
<% @events.each do |attending| %>
  <%= attending.event.name %> | <%= link_to 'unattend', unattend_event_path(:id => attending.event.id), class:"btn" %>
  <br>
<% end %>

app/views/events/new.html.erb
<% if @venues.count > 0 %>
  <%= render 'form' %>
<% else %>
  You must have a venue before you can create an event.
<% end %>

app/views/events/show.haml
= link_to 'BACK', :back
#event
  .panel.panel-default
    .panel-heading
      .panel-title
        = @event.name
    .panel-body
      = simple_format(word_wrap(@event.description,line_width: 60))
    .panel-footer
      %h4.company_title
        = @venue.name
      = @venue.address
      %br/
      = @venue.city
      = @venue.state
      = @venue.zip

app/views/home/_pages.haml
= link_to 'Previous page', {page: @pages[:page] - 1},class:"prev_page" unless @pages[:page] <= 1
= link_to 'Next page',{page: (@pages[:page] + 1)},class:"next_page" unless @pages[:page] >= @pages[:last_page]
%span
  page:
  = @pages[:page]
  out of
  = @pages[:last_page]

app/views/home/index.haml
- if current_user
  = link_to 'New Venue', new_venue_path, class:"btn"
  = link_to 'New Event', new_event_path, class:"btn"
  - if current_user.has_venues
    = link_to 'My Venues', venues_path, class:"btn"
  - if current_user.has_events
    = link_to 'My events', events_path, class:"btn"
%br/
%h2.title All Events
.page#page_content
  = render 'pages'
  .all-events#event_list
    - @events.each do|event|
      .panel.panel-default.index_events
        .avatar
          = image_tag "https://placekitten.com/g/96/140"
        %div{class:"event_#{event.id}"}
          .panel-heading
            .panel-title
              #{event.name}
          .panel-body
            @ #{event.venue.name}
            .event_buttons
              %span
                = link_to 'more_info', event_path(id:event.id), class: "show_event"
              - if current_user
                - if current_user.attending(event)
                  %span Attending! -
                  = link_to 'unattend', unattend_event_path(id:event.id),class:"unattend_#{event.id} unattend"
                - else
                  %span
                    = link_to 'attend', attend_event_path(id:event.id),class:"attend_#{event.id} attend"
  = render 'pages'
.event-info
  - flash.each do |name, msg|
    = content_tag :div, msg, class: name
  .event-text

app/views/home/old_index.html.erb
<% if current_user %>
  <%= link_to 'New Venue', new_venue_path %>
  <%= link_to 'New Event', new_event_path %>
  <% if current_user.has_venues %>
    | <%= link_to 'My Venues', venues_path %>
  <% end %>
  <% if current_user.has_events %>
    | <%= link_to 'My events', events_path %>
  <% end %>
<% end %>
<br><br>
<h2 class="title">All Events</h2>
<div class="all-events">
    <% @events.each do|event| %>
      <div class="panel panel-default">
          <div class="panel-body">
              <div class="<%= event.id %>">
                  <%= event.name %> at <%= event.venue.name %> <%= link_to 'more_info', event_path(id:event.id), class: "show" %>
                  <% if current_user %>
                    <% if current_user.attending(event) %>
                      - Attending! - <%= link_to 'unattend', unattend_event_path(id:event.id) %>
                    <% else %>
                      - <%= link_to 'attend', attend_event_path(:id => event.id) %>
                    <% end %>
                  <% end %>
                  <br>
              </div>
          </div>
      </div>
    <% end %>
</div>
<br>
<div class="event-info">
  <div class="panel"><div class="event-text"></div></div>
</div>
<%= link_to 'Previous page', page: @pages[:page] - 1 unless @pages[:page] <= 1%>
<%= link_to 'Next page', page: @pages[:page] + 1 unless @pages[:page] >= @pages[:last_page]%><br>
page: <%= @pages[:page] %> out of <%= @pages[:last_page] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="login">
      <%= link_to "Home", root_path %>
      <% if current_user %>
        <ul>
          <li><%= current_user.email %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        </ul>
      <% else %>
        <ul>
          <li><%= link_to "Login", login_path %></a></li>
          <li><%= link_to "Signup", signup_path %></a></li>
        </ul>
      <% end %>
  </div>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<%= yield %>
<div class="bottom"></div>
</body>
</html>

app/views/users/_form.html.erb
<%#= form_for(@user) do |f| %>
<%= simple_form_for(@user, html: {multipart: true, class: 'form-horizontal' }) do |f| %>
  <!--<#% if @event.errors.any? %>-->
  <!--<div id="error_explanation">-->
  <!--<h2><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>-->
  <!--<ul>-->
  <!--<%# @event.errors.full_messages.each do |message| %>-->
  <!--<li><%#= message %></li>-->
  <!--<%# end %>-->
  <!--</ul>-->
  <!--</div>-->
  <!--<%# end %>-->

  <div class="field">
    <%= f.text_field :first_name, :placeholder => "First name" %>
  </div>
  <div class="field">
    <%= f.text_field :last_name, :placeholder => "Last name" %>
  </div>
  <div class="field">
    <%= f.text_field :nickname, :placeholder => "User name" %>
  </div>
  <div class="field">
    <%= f.text_field :email, :placeholder => "Email" %>
  </div>
  <div class="field">
    <%= f.text_field :email_confirmation, :placeholder => "Email again" %>
  </div>
  <div class="field">
    <%= f.password_field :password_digest, :placeholder => "Password" %>
  </div>
  <div class="field">
    <%= f.password_field :password_digest_confirmation, :placeholder => "Password Again" %>
  </div>
  <div class="field">
    <%= f.text_field :info, :placeholder => "tag-line" %>
  </div>
  <div class="field">
    <%= f.text_field :bio, :placeholder => "Bio" %>
  </div>
  <!--<div class="field">-->
    <%#= f.label :avatar %><br>
    <!--<%#= f.file_field :avatar, as: :file %>-->
  <!--</div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <!--<#% if @event.errors.any? %>-->
    <!--<div id="error_explanation">-->
      <!--<h2><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>-->

      <!--<ul>-->
        <!--<%# @event.errors.full_messages.each do |message| %>-->
          <!--<li><%#= message %></li>-->
        <!--<%# end %>-->
      <!--</ul>-->
    <!--</div>-->
  <!--<%# end %>-->

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/index.html.erb
<%= link_to 'BACK', :back %><br>
<% @venues.each do|venue| %>
  <%= venue.name %>
  <%= link_to "delete", venue, method: "delete" %>
<% end %>

app/views/venues/new.html.erb
<%= render 'form' %>